name: DiamondBanking
version: ${project.version}
main: net.recelate.diamondbanking.DiamondBanking
api-version: 1.16
depend: [Vault]
authors: [Ellie]

commands:
  withdraw:
    description: Withdraw your money as Diamonds.
    usage: /withdraw [amount]
  deposit:
    description: Deposit the Diamonds in your main hand as Money.
    usage: /deposit
  dbreload:
    description: Reloads the DiamondBanking configuration.
    usage: /dbreload
    permission: diamondbanking.reload
    permission-message: You do not have permission to reload DiamondBanking.